### ISSUE TITLE
Improve Windows 10 labeling for OS version.

### ISSUE THREAD

**Issue by jetersen** [jenkinsci/platformlabeler-plugin#116]
Based on Docker experience with Windows it becomes increasingly important to build against the correct Windows 10 OS version.

Would be great to be able to label Windows Server 2019 and Windows 10 based on OS version such as 1803, 1809, 1903, 1909 etc :)

Other interesting bits: build number, build branch, install date :)

Here is one way to do this in powershell, not sure how to get `winver` to output to console.
```powershell
(Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").ReleaseId
```

This
```powershell
Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion"
```

Returns
```
SystemRoot                : C:\WINDOWS
BaseBuildRevisionNumber   : 1
BuildBranch               : 19h1_release
BuildGUID                 : ffffffff-ffff-ffff-ffff-ffffffffffff
BuildLab                  : 18362.19h1_release.190318-1202
BuildLabEx                : 18362.1.amd64fre.19h1_release.190318-1202
CompositionEditionID      : Enterprise
CurrentBuild              : 18362
CurrentBuildNumber        : 18362
CurrentMajorVersionNumber : 10
CurrentMinorVersionNumber : 0
CurrentType               : Multiprocessor Free
CurrentVersion            : 6.3
EditionID                 : Enterprise
EditionSubManufacturer    :
EditionSubstring          :
EditionSubVersion         :
InstallationType          : Client
InstallDate               : 1558501440
ProductName               : Windows 10 Enterprise
ReleaseId                 : 1903
SoftwareType              : System
UBR                       : 418
PathName                  : C:\Windows
ProductId                 : 00330-80000-00000-AA079
DigitalProductId          : {164, 0, 0, 0…}
DigitalProductId4         : {248, 4, 0, 0…}
InstallTime               : 132029750406990542
PSPath                    : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion
PSParentPath              : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT
PSChildName               : CurrentVersion
PSDrive                   : HKLM
PSProvider                : Microsoft.PowerShell.Core\Registry
```

**Comment by MarkEWaite** [comment]
Thanks for the suggestion!  Since the platformlabeler plugin is already willing to use the `lsb_release` command on Linux agents, I think it can optionally extend the definition of the version number with the value from the ReleaseId that can be read from the registry with the command:

```
C:\> REG QUERY "HKLM\Software\Microsoft\Windows NT\CurrentVersion" /t REG_SZ /v ReleaseId
```

Based on my reading of the [Windows commands reference](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/windows-commands), the `REG` command is available on Windows 8.1, Windows 10, Windows Server 2008 and later.

I think a new global setting and node specific setting should be added that allows the administrator to enable the version string for Windows agents to include the ReleaseId of the operating system.  Microsoft seems to call name it 'Windows 10, version 1903' and 'Windows Server, version 1903'.

Would the following label on a checkbox be clear to administrators (first line is the new addition):

* [ ] Include Windows feature release in Windows agent version numbers
* [ ] Generate label with OS architecture
* [ ] Generate label with OS name
* [ ] Generate label with OS version
* [ ] Generate label with OS architecture and name
* [ ] Generate label with OS name and version
* [ ] Generate label with OS architecture, name and version

**Comment by casz** [comment]
This is the markdown your looking for 😆 
```
[`REQ QUERY`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query)
```
produices
[`REQ QUERY`](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/reg-query)

**Comment by MarkEWaite** [comment]
I have a rough prototype working on a [development branch](https://github.com/MarkEWaite/platformlabeler-plugin/tree/add-windows-feature-release).  

My interactive testing found that the prototype is incorrectly requiring that the agent must override the settings in order to include the Windows feature update in the version string.  I'm sure that can be solved, but don't know when I will next have time to work on it.  I suspect it means that there is a more general purpose bug in the settings code which was only exposed by adding a label configuration flag that defaults to `false`.

**Comment by casz** [comment]
I may be able to contribute :)

**Comment by casz** [comment]
`override the settings`? Could to explain?

**Comment by MarkEWaite** [comment]
The platform labeler plugin provides global settings which enable and disable specific components of the labels.  Name, version, and architecture are the base components, then combinations of those.  

The prototype adds one more label configuration, to include the Windows feature update string in the version string.  For compatibility, that configuration is initially disabled.

Each agent may also individually define the label configuration for itself.

When I enable "include the Windows feature update string", it does not add the feature update string to Windows agents that were already defined.  It appears that the plugin somehow assumes that the agent definition (which is not actually defined for that Windows agent) overrides the global configuration.  If I define the platform label settings for the specific Windows agent and enable the "include the Windows feature update string", then the feature update string becomes visible on that agent.
